### ISSUE TITLE
deleted keys endpoint

### ISSUE THREAD

**Issue by dpaez** [hypergraph-xyz/vault#43]
Related to https://github.com/geut/permanent-seeder/issues/155

To complete the task described in https://github.com/geut/permanent-seeder/issues/155 the vault should expose a new endpoint with the deleted keys. There are no restrictions regarding the delete endpoint url. 

The expected output should look like this: `[ {url:"someHyperKey"} ]`  This is an array of objects containing at least one property, the `url` property, describing the deleted key. Other properties are admitted but they are ignored by the keys update mechanism.

**Comment by chartgerink** [comment]
Thanks @dpaez 😊 I'll add the route on Tuesday, after the local holidays.

**Comment by chartgerink** [comment]
@dpaez does it matter whether `someHyperKey` is denoted differently? For example:

1. `hyper://...`
2. `hypergraph://...`
3. `p2pcommons://...`

**Comment by dpaez** [comment]
> @dpaez does it matter whether `someHyperKey` is denoted differently? For example:
> 
> 1. `hyper://...`
> 2. `hypergraph://...`
> 3. `p2pcommons://...`

Hi chris, no it doesn't matter. We parse the values and work only with the keys internally.
